"""transactions table

Revision ID: b5b6c37a3f24
Revises: c71126d7adc2
Create Date: 2021-04-18 21:54:27.953909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b6c37a3f24'
down_revision = 'c71126d7adc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=64), nullable=True),
    sa.Column('recipient', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Float(precision=64), nullable=True),
    sa.Column('hash', sa.String(length=2400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('public_key', sa.String(length=2400), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'public_key')
    op.drop_table('transactions')
    # ### end Alembic commands ###
